source "https://rubygems.org"

gem "sinatra", "~> 2.1", ">= 2.1.0"

group :test do
  gem "rack-test", ">= 2.0.0"
  gem "rest-client"
  gem "rspec"
  gem "rspec_junit_formatter"
  gem "rubysl-securerandom"
end
